model_name: PredictSpruceForestsModel
model_path: ''

train: true
infer: false

pretrained: false
nn_framework: torch
batch_size: 12

data_specs:
  width: 650
  height: 650
  image_type: normalized
  rescale: false
  rescale_minima: auto
  rescale_maxima: auto
  channels: 3
  label_type: mask
  is_categorical: false
  mask_channels: 1
  val_holdout_frac: 0.2
  data_workers: 1

training_data_csv: '/scratch/project_2000599/johannes_version/tile_filepaths_for_training.csv'
validation_data_csv:
inference_data_csv: '/scratch/project_2000599/johannes_version/tile_filepaths_for_prediction.csv'

training_augmentation:
  augmentations:
    SwapChannels:
      axis: 2
      first_idx: 0
      second_idx: 2
      p: 1.0
    HorizontalFlip:
      p: 0.5
    RandomRotate90:
      p: 0.5
    RandomCrop:
      height: 512
      width: 512
      p: 1.0
    Normalize:
      mean:
        - 0.17395850358514
        - 0.035442982050778
        - 0.041676467416446
      std:
        - 0.10218734901152
        - 0.029166612631494
        - 0.02251037551648
      max_pixel_value: 1.0
      p: 1.0
  p: 1.0
  shuffle: true
validation_augmentation:
  augmentations:
    SwapChannels:
      axis: 2
      first_idx: 0
      second_idx: 2
      p: 1.0
    CenterCrop:
      height: 512
      width: 512
      p: 1.0
    Normalize:
      mean:
        - 0.17395850358514
        - 0.035442982050778
        - 0.041676467416446
      std:
        - 0.10218734901152
        - 0.029166612631494
        - 0.02251037551648
      max_pixel_value: 1.0
      p: 1.0
  p: 1.0
inference_augmentation:
  augmentations:
    SwapChannels:
      axis: 0
      first_idx: 0
      second_idx: 2
      p: 1.0
    Normalize:
      mean:
        - 0.17395850358514
        - 0.035442982050778
        - 0.041676467416446
      std:
        - 0.10218734901152
        - 0.029166612631494
        - 0.02251037551648
      max_pixel_value: 1.0
      p: 1.0
  p: 1.0
training:
  epochs: 500
  steps_per_epoch:
  optimizer: Adam
  lr: 0.01
  opt_args:
  loss:
    bcewithlogits:
    jaccard:
  loss_weights:
    bcewithlogits: 10
    jaccard: 2.5
  metrics:
    training:
    validation:
  checkpoint_frequency: 10
  callbacks:
    model_checkpoint:
      filepath: '/scratch/project_2000599/johannes_version/models/PredictSpruceBatchesModel.pth'
      monitor: val_loss
  model_dest_path: '/scratch/project_2000599/johannes_version/models/PredictSpruceBatchesModel_final.pth'
  verbose: true

inference:
  window_step_size_x:
  window_step_size_y:
  output_dir: ''
